version: '3.8'

services:
  translator-bot:
    build:
      context: .
      dockerfile: Dockerfile.example
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}
      - ADMIN_USER_ID=${ADMIN_USER_ID}
      - OPENAI_TTS_MODEL=${OPENAI_TTS_MODEL:-tts-1}
      - OPENAI_TTS_VOICE=${OPENAI_TTS_VOICE:-alloy}
      - DATABASE_PATH=/app/data/translator_bot.db
    volumes:
      - bot_data:/app/data
      - bot_cache:/app/data/cache
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - translator-net

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=translator_bot
      - POSTGRES_USER=bot_user
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - translator-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - translator-bot
    restart: unless-stopped
    networks:
      - translator-net

volumes:
  bot_data:
  bot_cache:
  postgres_data:

networks:
  translator-net:
    driver: bridge